name: Deploy Bot

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: SFTP Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: gamma.optiklink.com
        username: tc2j2dfz.6bd084e9
        password: ${{secrets.FTP_PASSWORD}}
        port: 2022
        uploads: |
          ./ => ./
        ignore: |
          *.git
          */**/*git*
          ./.vscode
    - name: Pterodactyl-Restart
      uses: supercrafter100/Pterodactyl-Restart@v1.0
      with:
        PTE_PANEL_URL: 'https://control.optiklink.com'
        PTE_BEARER_TOKEN: ${{ secrets.PTE_BEARER_TOKEN }}
        PTE_PANEL_ID: '6bd084e9'